
project_id = "ulfdphrinlzjlzejkyno"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false

[realtime]
enabled = false

[functions]
send-email = { verify_jwt = false }
send-smtp-email = { verify_jwt = false }
smtp-test-email = { verify_jwt = false }
