import React, { useState, useMemo } from 'react';
import FullCalendar from '@fullcalendar/react';
import dayGridPlugin from '@fullcalendar/daygrid';
import timeGridPlugin from '@fullcalendar/timegrid';
import interactionPlugin from '@fullcalendar/interaction';
import frLocale from '@fullcalendar/core/locales/fr.js';
import { TimeSlot } from '@/types';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import TimeSlotForm from './TimeSlotForm';
import DeleteConfirmation from './DeleteConfirmation';
import './fullcalendar.css'; // Import custom FullCalendar styles

interface TimeSlotCalendarProps {
  timeSlots: TimeSlot[];
  onEdit: (timeSlot: TimeSlot) => void;
  onDelete: (id: string) => Promise<void>;
  onCreate: (timeSlot: TimeSlot) => Promise<void>;
  loading?: boolean;
}

const TimeSlotCalendar: React.FC<TimeSlotCalendarProps> = ({
  timeSlots,
  onEdit,
  onDelete,
  onCreate,
  loading = false
}) => {
  const [selectedTimeSlot, setSelectedTimeSlot] = useState<TimeSlot | null>(null);
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);

  const handleCreateSubmit = async (timeSlotData: TimeSlot) => {
    let formattedDate: string | null = null;
    if (timeSlotData.specific_date) {
      if (typeof timeSlotData.specific_date === "string") {
        formattedDate = timeSlotData.specific_date;
      } else if (timeSlotData.specific_date instanceof Date) {
        formattedDate = timeSlotData.specific_date.toISOString().split('T')[0];
      }
    }

    const dataToSubmit = {
      ...timeSlotData,
      specific_date: formattedDate,
    };
    await onCreate(dataToSubmit);
    setIsCreateDialogOpen(false);
  };

  const handleEditSubmit = async (timeSlotData: TimeSlot) => {
    let formattedDate: string | null = null;
    if (timeSlotData.specific_date) {
      if (typeof timeSlotData.specific_date === "string") {
        formattedDate = timeSlotData.specific_date;
      } else if (timeSlotData.specific_date instanceof Date) {
        formattedDate = timeSlotData.specific_date.toISOString().split('T')[0];
      }
    }

    const dataToSubmit = {
      ...timeSlotData,
      specific_date: formattedDate,
    };
    await onEdit(dataToSubmit);
    setIsEditDialogOpen(false);
    setSelectedTimeSlot(null);
  };

  const handleEditClick = (timeSlot: TimeSlot) => {
    setSelectedTimeSlot(timeSlot);
    setIsEditDialogOpen(true);
  };

  const handleDelete = () => {
    if (selectedTimeSlot) {
      setDeleteId(selectedTimeSlot.id);
      setIsEditDialogOpen(false); // Close edit dialog before opening delete confirmation
    }
  };

  const handleDeleteConfirm = async () => {
    if (deleteId) {
      setIsDeleting(true);
      try {
        await onDelete(deleteId);
        setDeleteId(null);
        setSelectedTimeSlot(null); // Clear selection after delete
      } finally {
        setIsDeleting(false);
      }
    }
  };

  const calendarEvents = useMemo(() => {
    return timeSlots.map((slot) => {
      const event: any = {
        id: slot.id,
        title: slot.available ? 'Disponible' : 'Bloqué',
        allDay: false,
        extendedProps: { ...slot }, // Store original slot data
        className: slot.available ? 'available' : 'unavailable', // Use classes from fullcalendar.css
      };
      if (slot.is_recurring) {
        event.daysOfWeek = [slot.day_of_week];
        event.startTime = slot.startTime;
        event.endTime = slot.endTime;
        // For recurring events to show in month view, they might need a defined range
        // For now, they will show primarily in timeGrid views for the specific days.
      } else if (slot.specific_date) {
        event.start = `${slot.specific_date}T${slot.startTime}`;
        event.end = `${slot.specific_date}T${slot.endTime}`;
      }
      return event;
    });
  }, [timeSlots]);

  const handleEventClick = (clickInfo: any) => {
    const slot = clickInfo.event.extendedProps as TimeSlot;
    // The specific_date might be null for recurring events from extendedProps if not set initially
    // Ensure it has a valid value or default if needed by TimeSlotForm
     const preparedSlot = {
      ...slot,
      specific_date: slot.specific_date || new Date().toISOString().split('T')[0],
    };
    handleEditClick(preparedSlot);
  };
  
  const handleDateClick = (arg: any) => {
    // Open create dialog with the selected date
    // For simplicity, we use the existing "Ajouter un créneau" button logic
    // but this handler could be used to pre-fill the date
    console.log("Date clicked:", arg.dateStr);
    const newSlotInitialData: TimeSlot = {
        id: "", // Will be generated by backend or uuid
        day_of_week: new Date(arg.dateStr).getDay(), // Or keep as default
        startTime: "09:00",
        endTime: "10:00",
        available: true,
        is_recurring: false, // Default to non-recurring for a date click
        specific_date: arg.dateStr.split('T')[0] // Ensure only date part
    };
    // setSelectedTimeSlot(newSlotInitialData); // Not for edit, for create
    // setIsCreateDialogOpen(true); // This would work if TimeSlotForm handles initialData directly
    // For now, let's log and rely on the main button
    console.log("Suggested new slot data:", newSlotInitialData);
    setIsCreateDialogOpen(true); // Opens the standard create dialog
  };


  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex justify-between items-center mb-6">
        <h3 className="text-xl font-semibold text-gray-800">Calendrier des créneaux</h3>
        <Button onClick={() => setIsCreateDialogOpen(true)} className="bg-primary hover:bg-primary/90 text-white">
          Ajouter un créneau
        </Button>
      </div>

      <div className="bg-white rounded-lg border p-4 shadow-sm">
        <FullCalendar
          plugins={[dayGridPlugin, timeGridPlugin, interactionPlugin]}
          initialView="dayGridMonth"
          headerToolbar={{
            left: 'prev,next today',
            center: 'title',
            right: 'dayGridMonth,timeGridWeek,timeGridDay'
          }}
          events={calendarEvents}
          locale={frLocale}
          editable={false} // True if you want drag-and-drop event modification
          selectable={true} // True if you want to select dates/times
          eventClick={handleEventClick}
          dateClick={handleDateClick} // Allows creating events on date click
          height="auto" // Adjusts height to content or use a specific value like "600px"
          contentHeight="auto"
          slotMinTime="07:00:00" // Example: Show calendar from 7 AM
          slotMaxTime="22:00:00" // Example: Show calendar until 10 PM
          allDaySlot={false} // Hide "all-day" slot in timeGrid views if not needed
          nowIndicator={true}
        />
      </div>

      {/* Create Dialog */}
      <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Créer un nouveau créneau</DialogTitle>
          </DialogHeader>
          <TimeSlotForm
            // Provide minimal initialData for creation
            initialData={{
              id: "", 
              day_of_week: 1, // Default to Monday
              startTime: "09:00",
              endTime: "10:00",
              available: true,
              is_recurring: false, // Default to non-recurring
              specific_date: new Date().toISOString().split('T')[0] // Default to today
            }}
            onSubmit={handleCreateSubmit}
            onCancel={() => setIsCreateDialogOpen(false)}
            isEditing={false}
          />
        </DialogContent>
      </Dialog>

      {/* Edit Dialog */}
      <Dialog open={isEditDialogOpen} onOpenChange={(isOpen) => {
        setIsEditDialogOpen(isOpen);
        if (!isOpen) setSelectedTimeSlot(null); // Clear selection when dialog closes
      }}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Modifier le créneau</DialogTitle>
          </DialogHeader>
          {selectedTimeSlot && (
            <div className="space-y-4">
              <TimeSlotForm
                timeSlot={selectedTimeSlot} // Pass the full TimeSlot object
                onSubmit={handleEditSubmit}
                onCancel={() => {
                  setIsEditDialogOpen(false);
                  setSelectedTimeSlot(null);
                }}
                isEditing={true}
              />
              <div className="flex justify-end pt-4 border-t mt-4">
                <Button
                  variant="destructive"
                  onClick={handleDelete}
                  disabled={isDeleting}
                >
                  {isDeleting ? "Suppression..." : "Supprimer ce créneau"}
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation */}
      <DeleteConfirmation
        isOpen={!!deleteId}
        onClose={() => setDeleteId(null)}
        onConfirm={handleDeleteConfirm}
        isDeleting={isDeleting}
        title="Supprimer le créneau"
        description="Êtes-vous sûr de vouloir supprimer ce créneau ? Cette action est irréversible."
      />
    </div>
  );
};

export default TimeSlotCalendar;
