
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulfdphrinlzjlzejkyno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsZmRwaHJpbmx6amx6ZWpreW5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0ODQxNTYsImV4cCI6MjA2MzA2MDE1Nn0.ExV5y6UrmSxdL8hcJu0eCiOlA7u5ZKmKKTYiIw9ZGiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
